### ISSUE TITLE
Dozens of duplicate d4s2 share emails when keeping VM

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#148]
I'm putting this in lando since I believe that's where the call to D4S2Project.share() happens, but it could certainly be a bug in a different component

When I've set `job.cleanup_vm` to `False`, bespin sends me dozens of emails when the job is complete. I've seen this behavior both times in the last 6 months I've tried to debug a job by setting this flag to false.

I remarked on the first time in slack but can't remember exactly when it happened or if I filed an issue. it happened last week, but the messages got quarantined (see attached), and I didn't notice immediately.

![bespin-mailer-spam](https://user-images.githubusercontent.com/2752599/52303524-3ab33b00-295e-11e9-93f0-326faf54b209.png)

**Comment by johnbradley** [comment]
Based on my testing when we delete the queue the worker receives a duplicate copy of the last message.
Relevant code:
https://github.com/Duke-GCB/lando/blob/da2c40ef588578993a45c46f20676a691ef68067/lando/server/lando.py#L273-L276

If we are not deleting the vm we should probably leave the queue in place.
Not sure why deleting the queue causes the last message to replay.

**Comment by dleehr** [comment]
> Based on my testing when we delete the queue the worker receives a duplicate copy of the last message.

Nice digging. That certainly sounds like it would be related. Any idea why there were dozens of duplicate messages rather than just one?

**Comment by johnbradley** [comment]
The flow is like this:
1. LandoWorker receives the "save output" message, uploads project and sends LandoServer the "finished saving output".
2. LandoServer receives the "finished saving output" message,  deletes the LandoWorker's queue.
3. LandoWorker receives the phantom "save output" message, uploads nothing since it's done, sends LandoServer the "finished saving output" message, and listens on its queue.
4. go to step 2

Really you should have gotten infinity emails instead of dozens. At some point the phantom messages seem to stop.

I'm pretty sure the root cause is something wrong with lando-message/pika. Perhaps there is a flag that I should be checking on these phantom messages. Still digging.
